baseurl = "https://www.hugomint.com/"
title = "hugomint web design"
author = "Mr Mendes"
# google analyitics
googleAnalytics = "UA-152064338-1"
defaultContentLanguage = "en"
language = "en-US"
paginate = 4

theme = "fre"
# themesDir = "../.." # Not necessary on production sites

[taxonomies]
  taxonomy = "tags"
  # used for open graph
  series = "series"

[menu]
  [[menu.main]]

  [[menu.footer]]


[params]
  description = "Web design. Specialists in static websites and SEO. A web development company that has extensive experience in SEO (search engine optimisation). Improve your Google ranking."
  favicon = "favicon.ico"
  logo = ""
  images = ["site-feature-image.jpg"]
  title = "SEO"

[params.hero]
    textColor = "" # Empty for default color

[params.cta] # Call To Action 
    show = true
    cta = "Contact"
    link = "contact" # Relative URL

[params.separator] # Separators between sections on the home page
    show = true

[params.fa] # Font Awesome options
    version = "5.7.2"
    integrity = "sha384-0pzryjIRos8mFBWMzSSZApWtPl/5++eIfzYmTgBBmXYdhvxPc+XcFEk+zJwDgWbP"

[params.posts]
    showAuthor = true
    showDate = true
    showTags = true
    dateFormat = "Monday, Jan, 2006"

[params.social]
    twitter = "https://instagram.com/john"
    facebook = ""
    github = ""
    gitlab = ""
    codepen = ""
    instagram = ""
    pinterest = ""
    youtube = ""
    linkedin = ""
    weibo = ""
    mastodon = ""
    tumblr = ""
    flickr = ""
    "500px" = ""

[params.copy] # Copyright
    copy = "" # Empty for default content

[privacy]
    [privacy.googleAnalytics]
        anonymizeIP = true
        disable = false
        respectDoNotTrack = true
        useSessionStorage = false
    [privacy.instagram]
        disable = false
        simple = false
    [privacy.twitter]
        disable = false
        enableDNT = true
        simple = false
    [privacy.vimeo]
        disable = false
        simple = false
    [privacy.youtube]
        disable = false
        privacyEnhanced = true
